server:
  port: 8100
  servlet:
    session:
      timeout: 50400s

#热部署生效
spring:
  devtools:
    restart:
      enabled: true
      #设置重启的目录
      additional-paths: src/main/java,resources/**,static/**,templates/**
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
##  jpa:
##      show-sql: true
##      properties:
##        hibernate:
##          #指定oracle方言
##          #org.hibernate.dialect.Oracle9iDialect
##          #org.hibernate.dialect.Oracle10gDialect
##          #org.hibernate.dialect.Oracle12cDialect
##          dialect: org.hibernate.dialect.Oracle10gDialect
#  jpa:
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5Dialect
#
##jdbc:
##  datasource:
##    driver-class-name: oracle.jdbc.driver.OracleDriver
##    url: jdbc:oracle:thin:@10.1.51.215:1521:orcl
##    username: emergency_control
##    password: kingthis
#
#jdbc:
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://10.1.51.215:3306/emergency_control?useUnicode=true&characterEncoding=utf8&useSSL=false&zeroDateTimeBehavior=convertToNull
#    username: root
#    password: 123456
#    validation-query: select 1 from dual #指定获取连接时连接校验的sql查询语句
#    test-on-borrow: true #当从连接池借用连接时，是否测试该连接.
#    test-on-connect: true #创建时，是否测试连接
#    test-while-idle: true #当连接空闲时，是否执行连接测试.
#    time-between-eviction-runs-millis: 60000 #指定空闲连接检查、废弃连接清理、空闲连接池大小调整之间的操作时间间隔
#sf:
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://10.1.51.215:3306/basic?useUnicode=true&characterEncoding=utf8&useSSL=false&zeroDateTimeBehavior=convertToNull
#    username: root
#    password: 123456
#
#
#
#logging:
#  level:
#    root: INFO
#  path: /logs/area/ecc
#
#params:
#  title: 精密智控流调管理系统
#  portal:
#    mainUrl: http://10.1.51.211:5011
#    loginUrl: /login
#    logoutUrl: /logout
#    chooseUrl: /home/hsbpChoose
#    changePasswordUrl: /home/changePassword
#  #账号管理Url
#  userManageUrl: http://10.1.51.211:5011/user/edit
#  #角色分配Url
#  roleConfigUrl: http://10.1.51.211:5011/user/configRoles
#  #重置密码
#  initPassword: 123456
#  defaultRole:
#  #当前系统的子系统标识
#  sysCode: emergency-control
#  appKey: emergency-control
#  appSecret: 123
#  #超级管理员角色编码
#  devRoleCode: 6001
#  #区级审核人角色编码
#  areaReviewerRoleCode: 6006
#  #市级审核人角色编码
#  cityReviewerRoleCode: 6008
#  #录音文件保存绝对路径
##  soundsFilePath: /usr/local/ecc-sound-file/
#  soundsFilePath: D:\sound-path\
#  #录音文件最大限制（MB）
#  soundsFileMaxSize: 500
